blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Blog(models.Model):
    post_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('Blogger', on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(
        max_length=1000, help_text='Enter a content of the blog')

    class Meta:
        ordering = ['-post_date']

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse("blog-detail", args=[str(self.id)])

    def __str__(self):
        return self.title


class Blogger(models.Model):

    name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    bio = models.TextField(max_length=1000)

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse("blogger-detail", args=[str(self.id)])

    def __str__(self):
        return self.name.username


class Comment(models.Model):
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey('Blog', on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=100, help_text='Enter comment about blog here')
    commenter = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        return self.description

blog/views.py
from django.shortcuts import render
from .models import Blog, Blogger, Comment
from django.views import generic
# Create your views here.


def index(request):
    num_blogs = Blog.objects.count()
    num_bloggers = Blogger.objects.count()
    num_comments = Comment.objects.count()

    context = {
        'num_blogs': num_blogs,
        'num_bloggers': num_bloggers,
        'num_comments': num_comments,
    }

    return render(request, 'index.html', context=context)


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

    # def get_queryset(self):
    #     return Blog.objects.all().order_by('-post_date')

class BlogDetailView(generic.DetailView):
    model = Blog


class BloggerListView(generic.ListView):
    model = Blogger
    paginate_by = 5

class BloggerDetailView(generic.DetailView):
    model = Blogger

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Mini Blog</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'blogs' %}">All blogs</a></li>
                    <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="sidebar-nav col-sm-10 ">
                {% block content %}{% endblock %}
                {% block pagination %}
                {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
                {% endif %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ blog.title }}</h1>

<p><strong>Post date:</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blogger-detail' blog.author.pk %}">{{ blog.author }}</a></p>
<!-- author detail link not yet defined -->
<p><strong>Description:</strong><br> {{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
  <h4>Comments</h4>

  {% for comment in blog.comment_set.all %}
  <hr>
  <p>
    {{ comment.commenter.username }} ({{ comment.post_date }}) - {{ comment.description }}
  </p>
  {% endfor %}
  <hr>
  {% if user.is_authenticated %}
  <a href="#">Add a new comment</a>
  {% else %}
  <a href="#">Login</a> to add a new comment
  {% endif %}
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Mini Blog - Blog list</title>{% endblock %}
{% block content %}
  <h1>All blogs</h1>
  {% if blog_list %}
  <ul>
    {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{ blog.post_date.date }}) — <a href="{% url 'blogger-detail' blog.author.pk %}">{{ blog.author }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no posts in the mini blog.</p>
  {% endif %}       
{% endblock %}

blog/templates/blog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Blogger: {{ blogger.name.username }}</h1>
<div>
  <h3>Bio</h3>
</div>
<p>{{ blogger.bio }}</p>
<div>
  <h3>Blogs list</h3>
</div>

<ul>
  {% for blog in blogger.blog_set.all %}
  <li>
    <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{ blog.post_date.date }})
  </li>
  {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Mini Blog - Blog list</title>{% endblock %}
{% block content %}
  <h1>All bloggers</h1>
  {% if blogger_list %}
  <ul>
    {% for blogger in blogger_list %}
      <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.name.username }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no bloggers in the mini blog.</p>
  {% endif %}       
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
<title>Mini Blog - Home</title>
{% endblock %}

{% block content %}
<h1>Mini Blog Home</h1>
<h2>Dynamic content</h2>
<p>The mini blog has the following record counts</p>
<ul>
    <li><strong>Blogs:</strong> {{ num_blogs }}</li>
    <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
    <li><strong>Comments:</strong> {{ num_comments }}</li>
</ul>
{% endblock %}